apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srikanthhg/aisummarizer.git
    targetRevision: main
    path: charts/worker
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true